Neos:
  Form:
    presets:
      bootstrap:
        title: 'Bootstrap'
        parentPreset: default
        formElementTypes:
          'Neos.Form:FormElement':
            properties:
              labelClassAttribute: ''
              containerClassAttribute: 'form-group'
              containerInnerClassAttribute: ''
              elementClassAttribute: form-control
              elementErrorClassAttribute: has-error
              elementType: text
